# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia"

apache_fallback_resource: "/index.php"

command:
  init:
    - "composer update"

  update-offline:
    - "rm -Rf /opt/offline-www/* && wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P /opt/offline-www http://localhost && mv  /opt/offline-www/localhost/* /opt/offline-www &&  git add ."
