# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia"

apache_fallback_resource: "/index.php"

command:
  init:
    - "composer update"

  dev:
    - "rm -Rf /opt/docs/* && wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P /opt/docs http://localhost && mv  /opt/docs/localhost/* /opt/docs &&  git add ."
